### ISSUE TITLE
感谢作者工作，跑demo碰到以下问题，期待回复

### ISSUE THREAD

**Issue by uacovz** [vision4robotics/CDT#1]
"D:\Program Files\anaconda3\envs\cdt\python.exe" D:\learn_experiment\CDT-main\demo.py 
Traceback (most recent call last):
  File "D:\learn_experiment\CDT-main\demo.py", line 28, in <module>
    cdt = Denoiser(model, args)
  File "D:\learn_experiment\CDT-main\denoiser\denoiser_builder.py", line 20, in __init__
    self.model.load_state_dict(checkpoint['params'])
KeyError: 'params'

进程已结束,退出代码1

环境：
torch11.0
显卡 3060
win11

**Comment by L-KH97** [comment]
Thank you for your attention and question.
Please make sure the model you are using is the provided CDT model.
The link to download the model is: https://pan.baidu.com/s/1pC_B6wKYVIA8Z7ljBp7t-A?pwd=cdtn .

感谢您的关注及提问。
请确保您使用的模型是所提供的CDT模型。
模型下载链接为： https://pan.baidu.com/s/1pC_B6wKYVIA8Z7ljBp7t-A?pwd=cdtn 。
