### ISSUE TITLE
请问CDT方法的跟踪速度是多少？论文中好像没有体现。

### ISSUE THREAD

**Issue by whjzsy** [vision4robotics/CDT#3]

**Comment by L-KH97** [comment]
Thank you for your attention and question.
Please refer to IV. G Real-World Tests. When combined with a tracker and an enhancer, CDT can reach more than 20FPS.

感谢您的关注及提问。
请参阅IV. G Real-World Tests。CDT方法在和跟踪器与增强器结合的部署中，能到达20FPS以上的运行速度。
